- name: "HIGH | RHEL-07-010010 | AUDIT | The file permissions, ownership, and group membership of system files and commands must match the vendor values."
  shell: 'rpm -Va | grep ''^.M'''
  args:
    warn: no
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010010_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-010010
    - always
    - rpm

- name: "HIGH | RHEL-07-010020 | AUDIT | The cryptographic hash of system files and commands must match vendor values."
  shell: 'rpm -Va | grep ''^..5'' | grep -E ''/.?bin/'''
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010020_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-010020
    - always

- name: "HIGH | RHEL-07-010480 | AUDIT | Systems with a Basic Input/Output System (BIOS) must require authentication upon booting into single-user and maintenance modes."
  command: grep -i ^password_pbkdf2 /boot/grub2/grub.cfg
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010480_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-010480
    - always

- name: "HIGH | RHEL-07-010490 | AUDIT | Systems using Unified Extensible Firmware Interface (UEFI) must require authentication upon booting into single-user and maintenance modes."
  command: grep -i ^password_pbkdf2 /boot/efi/EFI/redhat/grub.cfg
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010490_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-010490
    - always

- name: "HIGH | RHEL-07-020170 | PATCH | Operating systems handling data requiring data-at-rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest."
  shell: blkid | grep -vi crypto_LUKS
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_020170_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-020170

- name: "HIGH | RHEL-07-020310 | AUDIT | The root account must be the only account having unrestricted access to the system."
  command: 'awk -F: ''$3 == 0 && $1 !~ /root/ {print $1}'' /etc/passwd'
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_020310_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-020310
    - always

- name: "HIGH | RHEL-07-040540 | AUDIT | There must be no .shosts files on the system."
  find:
    paths: /
    recurse: yes
    hidden: yes
    patterns: '*.shosts'
  register: rhel_07_040540_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-040540
    - always

- name: "HIGH | RHEL-07-040550 | AUDIT | There must be no shosts.equiv files on the system."
  find:
    paths: /
    recurse: yes
    patterns: shosts.equiv
  register: rhel_07_040550_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-040550
    - always

- name: "HIGH | RHEL-07-040800 | AUDIT | SNMP community strings must be changed from the default."
  command: grep {{ item }} /etc/snmp/snmpd.conf
  failed_when: no
  changed_when: no
  ignore_errors: yes
  with_items:
    - public
    - private
  register: rhel_07_040800_audit
  tags:
    - cat1
    - high
    - audit
    - RHEL-07-040800
    - always
    - snmp
