- name: "MEDIUM | RHEL-07-040180 | AUDIT | The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) authentication communications."
  command: grep -i useldapauth /etc/sysconfig/authconfig
  register: rhel_07_040180_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat2
    - medium
    - audit
    - RHEL-07-040180
    - ldap
    - always

- name: "MEDIUM | RHEL-07-040500 | AUDIT | The operating system must, for networked systems, synchronize clocks with a server that is synchronized to one of the redundant United States Naval Observatory (USNO) time servers, a time server designated for the appropriate DoD network (NIPRNet/SIPRNet), and/or the Global Positioning System (GPS)."
  stat:
    path: /etc/ntp.conf
  register: rhel_07_040500_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat2
    - medium
    - audit
    - RHEL-07-040500
    - ntpd
    - always

- name: "MEDIUM | RHEL-07-040230 | AUDIT | The operating system, if using PKI-based authentication, must implement a local cache of revocation data to certificate validation in case of the inability to access revocation information via the network."
  stat:
    path: /var/lib/pki-kra/conf/server.xml
  register: rhel_07_040230_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
    - cat2
    - medium
    - audit
    - RHEL-07-040230
    - always
    - pki

- name: "MEDIUM | RHEL-07-040420 | AUDIT | The SSH private host key files must have mode 0600 or less permissive."
  find:
    paths: /
    recurse: yes
    file_type: file
    patterns: '*ssh_host*key'
    hidden: true
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_040420_audit
  tags:
    - cat2
    - high
    - audit
    - RHEL-07-040420
    - always
    - ssh

- name: "MEDIUM | RHEL-07-040410 | AUDIT | The SSH public host key files must have mode 0644 or less permissive."
  find:
    paths: /
    recurse: yes
    file_type: file
    patterns: '*.pub'
    hidden: true
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_040410_audit
  tags:
    - cat2
    - high
    - audit
    - RHEL-07-040410
    - always
    - ssh

- name: "MEDIUM | RHEL-07-041010 | AUDIT | Wireless network adapters must be disabled."
  command: nmcli radio wifi
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_041010_audit
  tags:
    - cat2
    - high
    - audit
    - RHEL-07-041010
    - always

- name: "MEDIUM | RHEL-07-010030 | AUDIT | The operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon. "
  shell: 'test -d /etc/dconf/db/local.d; if [ $? == 0 ]; then grep -s -i banner-message-enable /etc/dconf/db/local.d/* | grep -i false; fi'
  register: rhel_07_010030_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
   - cat2
   - medium
   - audit
   - RHEL-07-010030
   - gui
   - always

- name: "MEDIUM | RHEL-07-010040 | AUDIT | The operating system must display the approved Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon. "
  shell: 'test -d /etc/dconf/db/local.d; if [ $? == 0 ]; then grep -s -i banner-message-text/etc/dconf/db/local.d/*; fi'
  register: rhel_07_010040_audit
  failed_when: no
  changed_when: no
  ignore_errors: yes
  tags:
   - cat2
   - medium
   - audit
   - RHEL-07-010040
   - gui
