- name: "LOW | RHEL-07-020200 | PATCH | The operating system must remove all software components after updated versions have been installed."
  command: "true"
  tags:
    - cat3
    - low
    - patch
    - RHEL-07-020200

- name: "LOW | RHEL-07-020300 | PATCH | All Group Identifiers (GIDs) referenced in the /etc/passwd file must be defined in the /etc/group file."
  command: "true"
  tags:
    - cat3
    - low
    - patch
    - RHEL-07-020300

- name: "LOW | RHEL-07-021600 | PATCH | The file integrity tool must be configured to verify Access Control Lists (ACLs)."
  command: "true"
  tags:
    - cat3
    - low
    - patch
    - RHEL-07-021600

- name: "LOW | RHEL-07-021610 | PATCH | The file integrity tool must be configured to verify extended attributes."
  command: "true"
  tags:
    - cat3
    - low
    - patch
    - RHEL-07-021610

- name: "LOW | RHEL-07-040300 | PATCH | The system must display the date and time of the last successful account logon upon logon."
  command: "true"
  tags:
    - cat3
    - low
    - patch
    - RHEL-07-040300

- name: "LOW | RHEL-07-040320 | PATCH | For systems using DNS resolution, at least two name servers must be configured."
  command: "true"
  tags:
    - cat3
    - low
    - patch
    - RHEL-07-040320

